site_name: test-doc-portal1
site_description: Test Doc Portal Documentation
theme:
  name: material
  features:
   - navigation.top
   - navigation.expand
   - navigation.sections
   - navigation.indexes
   - header.autohide
   - announce.dismiss
plugins:
  - techdocs-core
  - search
  - tags
  - autotag:
      globs:
        "debug-guide.md": "debug"
        "integration-guide.md": "integration"
markdown_extensions: 
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true
