site_name: test-doc-portal1
site_description: Test Doc Portal Documentation
theme:
  name: material
  features:
   - navigation.top
   - navigation.expand
   - navigation.sections
   - navigation.indexes
   - header.autohide
   - announce.dismiss
   - search.suggest
   - search.highlight
   - search.share
plugins:
  - techdocs-core
  - search
  - tags
  - autotag:
      globs:
        "debug-guide.md": "debug"
        "integration-guide.md": "integration"
        "runbooks.md": "debug"
markdown_extensions: 
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true
